- action:
  - alias: Turn on bathroom lights
    service: script.bathroom_motion_timer
  alias: Bathroom Motion Detected
  id: '1502419040930'
  trigger:
  - entity_id: binary_sensor.eye_motion_71
    platform: state
    from: 'off'
    to: 'on'
  - hide_entity: true

