- action:
  - alias: Turn on bathroom lights
    service: script.bathroom_motion_timer
  hide_entity: True
  alias: Bathroom Motion Detected
  id: '1502419040930'
  trigger:
  - entity_id: binary_sensor.eye_motion_71
    platform: state
    from: 'off'
    to: 'on'

- action:
  - alias: Turn on basement stairwell lights
    service: script.basement_stair_motion_timer
  hide_entity: True
  alias: Stairwell Motion Detected
  id: 'jwe002'
  trigger:
  - entity_id: binary_sensor.stairway_motion_80
    platform: state
    from: 'off'
    to: 'on'
