homeassistant:
  # Name of the location where Home Assistant is running
  name: HoneyHaus
  # Location required to calculate the time the sun rises and sets
  latitude: 39.030158
  longitude: -94.673839
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 294
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.1.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore: google_cast

hassio:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# logger:
#   default: debug
    
# Track the sun
sun:

ios:
  notify:
  - platform: ios 
    name: iOSApp
    target: je_iphone

device_tracker:
  - platform: nmap_tracker
    track_new_devices: false
    hosts: 192.168.1.0/24
    interval_seconds: 30

# Text to speech
# tts:  
#   - platform: google
#     language: "en"
#     base_url: !secret duck_url

# media_player:
#   - platform: cast

apple_tv:
  - host: 192.168.1.120
    login_id: !secret apple_tv_id
    start_off: true

vera:
  vera_controller_url: http://192.168.1.153:3480
  exclude: [34]
  lights: [53]

binary_sensor:
  - platform: workday
    country: US
    province: KS

shopping_list:

# weblink: 
#   entities: 
#   - name: Trigger Button
#     url: https://honeyhaus.duckdns.org/api/

# mqtt:
#   broker: 172.17.0.1

# hdmi_cec:
#   devices:
#     TV: 0.0.0.0
#     Google: 1.0.0.0
#     ATV: 0.0.1.0

sensor: !include_dir_merge_list sensors
scene: !include_dir_merge_list scenes
group: !include groups.yaml
automation: !include automations.yaml
zone: !include zones.yaml
script: !include scripts.yaml
