homeassistant:
  name: HoneyHaus
  latitude: !secret ha_lat
  longitude: !secret ha_lon
  elevation: !secret ha_ele
  unit_system: imperial
  time_zone: America/Chicago
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
    - type: trusted_networks

  # load packages (split-configuration format)
  packages: !include_dir_named components

  # customize individual entries
  customize: !include_dir_merge_named customizations

# # Discover some devices automatically
# discovery:
#   ignore: google_cast


light:
  - platform: group
    name: Bathroom Lights
    entities:
      - light.bathroom_bulb_1
      - light.bathroom_bulb_2
      - light.bathroom_bulb_3
      - light.bathroom_bulb_4

binary_sensor:
  - platform: workday
    country: US
    province: KS

device_tracker: !include_dir_merge_list device_tracker
sensor: !include_dir_merge_list sensors
input_boolean: !include_dir_merge_named input_boolean
scene: !include_dir_merge_list scenes
script: !include scripts.yaml
automation: !include_dir_merge_list automation
zone: !include zones.yaml
notify: !include_dir_merge_list notification
group: !include_dir_merge_named groups
