homeassistant:
  name: HoneyHaus
  latitude: 39.030158
  longitude: -94.673839
  elevation: 294
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml

frontend:

config:

http:
  api_password: !secret http_password
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.1.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 5
  base_url: honeyhaus.duckdns.org

updater:
  include_used_components: true

# Discover some devices automatically
discovery:
  ignore: google_cast

hassio:

shopping_list:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  exclude: 
    entities: 
      - device_tracker.withings_scale
      - remote.apple_tv
      - sensor.moon
      - sensor.ssl_certificate_expiry
    domains: 
      - group
      - sun

# View all events in a logbook
logbook:
  exclude: 
    entities:
       - sensor.local_time
       - sensor.weather_symbol
    domains: 
      - sun

# logger:
#   default: debug
    
# Track the sun
sun:

ios:
  notify:
  - platform: ios 
    name: iOSApp
    target: je_iphone

device_tracker:
  - platform: nmap_tracker
    track_new_devices: false
    hosts: 
      - 192.168.1.112
      - 192.168.1.234
      - 192.168.1.219
    interval_seconds: 15

apple_tv:
  - host: 192.168.1.120
    login_id: !secret apple_tv_id
    start_off: true

vera:
  vera_controller_url: http://192.168.1.153:3480
  exclude: [34, 95, 96]
  lights: [53]

binary_sensor:
  - platform: workday
    country: US
    province: KS

sensor: !include_dir_merge_list sensors
scene: !include_dir_merge_list scenes
group: !include groups.yaml
automation: !include automations.yaml
zone: !include zones.yaml
script: !include scripts.yaml
