homeassistant:
  name: HoneyHaus
  latitude: !secret ha_lat
  longitude: !secret ha_lon
  elevation: !secret ha_ele
  unit_system: imperial
  time_zone: America/Chicago
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
    - type: trusted_networks

  # load packages (split-configuration format)
  packages: !include_dir_named components

  # customize individual entries
  customize: !include customize.yaml

# # Discover some devices automatically
# discovery:
#   ignore: google_cast

device_tracker:
  - platform: nmap_tracker
    track_new_devices: true
    hosts: 
      - 192.168.1.31
      - 192.168.1.110
      - 192.168.1.128
      - 192.168.1.111
    interval_seconds: 15

light:
  - platform: group
    name: Bathroom Lights
    entities:
      - light.bathroom_bulb_1
      - light.bathroom_bulb_2
      - light.bathroom_bulb_3
      - light.bathroom_bulb_4

binary_sensor:
  - platform: workday
    country: US
    province: KS

input_boolean:
  enable_security: 
    name: Alarm Enabled
    icon: mdi:shield-outline
    initial: on
  vacation_mode: 
    name: Vacation Mode
    icon: mdi:airplane
    initial: off
  status_in_bed: 
    name: In Bed
    icon: mdi:hotel
    initial: off

notify:
  - name: honeyhausha
    platform: twitter
    consumer_key: !secret twitter_ha_consumer_key
    consumer_secret: !secret twitter_ha_consumer_secret
    access_token: !secret twitter_ha_access_token
    access_token_secret: !secret twitter_ha_access_token_secret

automation: !include automations.yaml
group: !include_dir_merge_named groups
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors
scene: !include_dir_merge_list scenes
zone: !include zones.yaml
