title: Honey Haus
resources:
  - url: /local/tracker-card.js?v=0.1.5
    type: js
  - url: /local/monster-card.js?v=0.2.3
    type: js

views:
  - title: Home
    id: home
    icon: mdi:home-assistant
    background: radial-gradient(green,blue)
    cards:
      - id: home_1
        type: entity-filter
        entities:
          - device_tracker.je_iphone
          - device_tracker.rb_iphone
        state_filter:
          - home
        card:
          type: glance
          title: Home

  - title: Weather
    id: weather
    icon: mdi:weather-partlycloudy
    cards:
      - id: weather_1
        type: weather-forecast
        entity: weather.dark_sky

  - title: Living Room
    id: living
    icon: mdi:sofa
    cards:
      - id: living_1
        type: light
        entity: light.north_can_light_63
        name: North Can Light
      - id: living_2
        type: light
        entity: light.south_can_light_65
        name: South Can Light

  - title: Dining Room
    id: dining
    icon: mdi:silverware
    cards:
      - id: dining_1
        type: light
        entity: light.chandelier_10
        name: Chandelier
      - id: dining_2
        type: thermostat
        entity: climate.thermostat_4

  - title: Plants
    id: plants
    icon: mdi:flower
    cards:
      - id: plant_1
        type: plant-status
        entity: plant.pineapple
      - id: plant_2
        type: plant-status
        entity: plant.banana
      - id: plant_3
        type: plant-status
        entity: plant.ficus
      - id: plant_4
        type: plant-status
        entity: plant.philodendron

  - title: Settings
    id: settings
    icon: mdi:settings
    cards:
      - id: settings_1
        type: custom:monster-card
        show_empty: false
        card:
          id: settings_1_1
          type: glance
          title: Low Battery Devices
        filter:
          include:
            - attributes:
                battery_level: < 25
            - attributes:
                battery: < 25
          exclude:
            - entity_id: sensor.home_energy_monitor_98
      - id: settings_2
        type: custom:monster-card
        show_empty: false
        card:
          id: settings_2_1
          type: entities
          title: Broken?
        filter:
          include:
            - state: unknown
            - state: unavailable
          exclude:
            - entity_id: group.*
      - id: settings_3
        type: custom:tracker-card
        trackers:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker
          - sensor.custom_python_script_tracker
