title: Honey Haus
resources:
  - url: /local/tracker-card.js?v=0.1.5
    type: js
  - url: /local/monster-card.js?v=0.2.3
    type: js

views:
  - title: Home
    icon: mdi:home-assistant
    id: home
    background: radial-gradient(green,blue)
    cards:
      - id: 2f1682241ea546e6a908a3452e154d73  # Automatically created id
        type: entity-filter
        entities:
          - device_tracker.je_iphone
          - device_tracker.rb_iphone
        state_filter:
          - home
        card:
          type: glance
          title: Home

  - title: Weather
    icon: mdi:weather-partlycloudy
    id: weather
    cards:
      - id: 1e67401def4c42919aca0a5cb37b386d  # Automatically created id
        type: weather-forecast
        entity: weather.dark_sky

  - title: Living Room
    icon: mdi:sofa
    cards: 
      - type: light
        entity: light.north_can_light_63
        name: North Can Light
      - type: light
        entity: light.south_can_light_65
        name: South Can Light

  - title: Dining Room
    icon: mdi:silverware
    cards: 
      - type: light
        entity: light.chandelier_10
        name: Chandelier
      - type: thermostat
        entity: climate.thermostat_4

  - title: Settings
    icon: mdi:settings
    id: settings
    cards:
      - id: 497f6a4ba7e848fc8d14b27ec90bfc52  # Automatically created id
        type: custom:monster-card
        show_empty: false
        card:
          type: glance
          title: Low Battery Devices
        filter:
          include:
            - attributes:
                battery_level: < 25
            - attributes:
                battery: < 25
          exclude:
            - entity_id: sensor.home_energy_monitor_98
      - id: da181784eecb4e25b451c60d808bf0be  # Automatically created id
        type: custom:monster-card
        show_empty: false
        card:
          type: entities
          title: Broken?
        filter:
          include:
            - state: unknown
            - state: unavailable
          exclude:
            - entity_id: group.*
      - id: 4d519740e9b9440684d4a3c0019ac2d8  # Automatically created id
        type: custom:tracker-card
        trackers:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker
          - sensor.custom_python_script_tracker
