---
# Weather
- platform: yr
  name: Weather
  monitored_conditions:
    - temperature
    - symbol

# Have I Been Pwned
- platform: haveibeenpwned
  email:
    - !secret pwned_email_1
    - !secret pwned_email_2
    - !secret pwned_email_3