# Weather
- platform: yr
  name: Weather
  monitored_conditions: 
    - temperature
    - symbol
    
# Have I Been Pwned
- platform: haveibeenpwned
  email: 
    - !secret pwned_email_1
    - !secret pwned_email_2
    - !secret pwned_email_3

# Air Visual
- platform: airvisual
  api_key: !secret airvisual_key
  monitored_conditions: us

# Moon Information
- platform: moon

# Season
- platform: season
  type: astronomical

# DarkSky Entries
- platform: darksky
  api_key: !secret darksky_key
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
- platform: template
  sensors:
    dark_sky_template:
      value_template: "{{ states('sensor.dark_sky_summary') }}"
      icon_template: >
        {% if is_state('sensor.dark_sky_icon', 'clear-day') %}
          mdi:weather-sunny
        {% elif is_state('sensor.dark_sky_icon', 'clear-night') %}
          mdi:weather-night
        {% elif is_state('sensor.dark_sky_icon', 'rain') %}
          mdi:weather-rainy
        {% elif is_state('sensor.dark_sky_icon', 'snow') %}
          mdi:weather-snowy
        {% elif is_state('sensor.dark_sky_icon', 'sleet') %}
          mdi:weather-snowy-rainy
        {% elif is_state('sensor.dark_sky_icon', 'wind') %}
          mdi:weather-windy-variant
        {% elif is_state('sensor.dark_sky_icon', 'fog') %}
          mdi:weather-fog
        {% elif is_state('sensor.dark_sky_icon', 'cloudy') %}
          mdi:weather-cloudy
        {% elif is_state('sensor.dark_sky_icon', 'partly-cloudy-day') or is_state('sensor.dark_sky_icon', 'partly-cloudy-night') %}
          mdi:weather-partlycloudy
        {% elif is_state('sensor.dark_sky_icon', 'hail') %}
          mdi:weather-hail
        {% elif is_state('sensor.dark_sky_icon', 'thunderstorm') %}
          mdi:weather-lightning
        {% else %}
          mdi:help-circle
        {% endif %}

# World Clock
- platform: worldclock
  name: Local Time
  time_zone: America/Chicago

# Bathroom Time Adjustment for Morning
# - platform: template
#   sensors: 
#     bathroom_delay:
#       value_template: > 
#           {% if (states.sensor.local_time.state > "05:00") and (states.sensor.local_time.state < "10:00") %}
#             15
#           {% else %}
#             5
#           {% endif %}
