- platform: yr
  name: Weather
  monitored_conditions: 
    - temperature
    - symbol
- platform: moon
- platform: darksky
  api_key: !secret dark_sky_key
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - minutely_summary