# Weather
- platform: yr
  name: Weather
  monitored_conditions: 
    - temperature
    - symbol
    
# Have I Been Pwned
- platform: haveibeenpwned
  email: 
    - !secret pwned_email_1
    - !secret pwned_email_2
    - !secret pwned_email_3

# Air Visual
- platform: airvisual
  api_key: !secret airvisual_key
  monitored_conditions: us
  show_on_map: false
 

# Moon Information
- platform: moon

# Season
- platform: season
  type: astronomical

# DarkSky Entries
- platform: darksky
  api_key: !secret darksky_key
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - humidity
    - visibility
    - uv_index
    - precip_probability
    - precip_accumulation
- platform: template
  sensors:
    dark_sky_template:
      value_template: "{{ states('sensor.dark_sky_summary') }}"
      icon_template: >
        {% if is_state('sensor.dark_sky_icon', 'clear-day') %}
          mdi:weather-sunny
        {% elif is_state('sensor.dark_sky_icon', 'clear-night') %}
          mdi:weather-night
        {% elif is_state('sensor.dark_sky_icon', 'rain') %}
          mdi:weather-rainy
        {% elif is_state('sensor.dark_sky_icon', 'snow') %}
          mdi:weather-snowy
        {% elif is_state('sensor.dark_sky_icon', 'sleet') %}
          mdi:weather-snowy-rainy
        {% elif is_state('sensor.dark_sky_icon', 'wind') %}
          mdi:weather-windy-variant
        {% elif is_state('sensor.dark_sky_icon', 'fog') %}
          mdi:weather-fog
        {% elif is_state('sensor.dark_sky_icon', 'cloudy') %}
          mdi:weather-cloudy
        {% elif is_state('sensor.dark_sky_icon', 'partly-cloudy-day') or is_state('sensor.dark_sky_icon', 'partly-cloudy-night') %}
          mdi:weather-partlycloudy
        {% elif is_state('sensor.dark_sky_icon', 'hail') %}
          mdi:weather-hail
        {% elif is_state('sensor.dark_sky_icon', 'thunderstorm') %}
          mdi:weather-lightning
        {% else %}
          mdi:help-circle
        {% endif %}

# World Clock
- platform: worldclock
  name: Local Time
  time_zone: America/Chicago

# pollen.com
- platform: pollen
  zip_code: "66202"
  monitored_conditions:
    - allergy_average_forecasted
    - allergy_average_historical
    - allergy_index_today
    - allergy_index_tomorrow
    - allergy_index_yesterday
    - disease_average_forecasted

