- platform: miflora
  mac: 'C4:7C:8D:67:69:A4'
  name: Pinapple
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

- platform: miflora
  mac: 'C4:7C:8D:67:68:B3'
  name: Ficus
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

- platform: miflora
  mac: 'C4:7C:8D:67:68:AF'
  name: Banana
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

- platform: miflora
  mac: 'C4:7C:8D:67:68:F4'
  name: Philodendron
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery
