# Raspberry Pi Information
- platform: systemmonitor
  resources: 
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: processor_use

# Network Speed Test
- platform: speedtest
  hour:
    - 8
    - 12
    - 16
    - 20
  monitored_conditions:
    - download
    - upload

# HA Version
- platform: version

# HA Certificate Expiry
- platform: cert_expiry
  host: honeyhaus.duckdns.org

