---
# Raspberry Pi Information
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_free
      arg: /
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free
    - type: processor_use
    - type: last_boot
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0

# Network Speed Test
# - platform: speedtest
#   hour:
#     - 8
#     - 12
#     - 16
#     - 20
#   monitored_conditions:
#     - ping
#     - download
#     - upload

# HA Version
# The version sensor platform is displaying the
# available version online.
#
# https://www.home-assistant.io/components/sensor.version/
#
- platform: version
- platform: uptime

# HA Certificate Expiry
- platform: cert_expiry
  host: !secret duck_url
