---
- alias: BP Med Taken
  hide_entity: true
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: BP_TABLET_TAKEN
  action:
    - service: notify.ios_je_iphone
      data_template:
        message: >
          {{
            [
              "Good Job!",
              "Your ❤️ thanks you!",
              "Fist bump, bro!",
              "Thanks for taking care of your blood pressure!",
              "Way to go!"
            ] | random
          }}
    - service: input_boolean.turn_on
      entity_id: input_boolean.bp_medicine

- alias: BP Remind Me Later
  hide_entity: true
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: BP_TABLET_SNOOZE
  action:
    - service: notify.ios_je_iphone
      data:
        message: "Ok. I will remind you later..."

- alias: BP Medicine Reminder
  hide_entity: true
  initial_state: true
  trigger:
    - platform: time_pattern
      minutes: "/15"
      seconds: "00"
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.bp_medicine
          state: "off"
        - condition: time
          after: "06:30:00"
  action:
    - service: notify.ios_je_iphone
      data:
        title: "BP Medicine Alert!"
        message: "Please take your BP Medicine!"
        data:
          push:
            category: "bp_med"
            # action_data:
            #   entity_id: light.test
            #   my_custom_dat: foo_bar

- alias: BP Medicine Reset
  hide_entity: true
  trigger:
    - platform: time
      at: "01:00:00"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.bp_medicine
