- alias: Medicine Reset
  trigger: 
    - platform: time
      at: '01:00:00'
  action: 
    - service: input_number.set_value
      data_template: 
        entity_id: input_number.antibiotic
        value: 0

# - alias: Medicine 1
#   trigger:
#     - platform: time
#       minutes: '/15'
#       seconds: '00'
#   condition:
#     condition: and
#     conditions: 
#       - condition: numeric_state
#         entity_id: input_number.antibiotic
#         below: 1
#       - condition: time
#         after: '06:00:00'
#   action: 
#     - service: notify.ios_je_iphone
#       data: 
#         title: 'Medicine Alert'
#         message: 'Please take your pill'
#         data: 
#           push: 
#             category: 'temp_med'

# - alias: Medicine 2
#   trigger:
#     - platform: time
#       minutes: '/15'
#       seconds: '00'
#   condition:
#     condition: and
#     conditions: 
#       - condition: numeric_state
#         entity_id: input_number.antibiotic
#         below: 2
#       - condition: time
#         after: '11:00:00'
#   action: 
#     - service: notify.ios_je_iphone
#       data: 
#         title: 'Medicine Alert'
#         message: 'Please take your pill'
#         data: 
#           push: 
#             category: 'temp_med'

# - alias: Medicine 3
#   trigger:
#     - platform: time
#       minutes: '/15'
#       seconds: '00'
#   condition:
#     condition: and
#     conditions: 
#       - condition: numeric_state
#         entity_id: input_number.antibiotic
#         below: 3
#       - condition: time
#         after: '16:00:00'
#   action: 
#     - service: notify.ios_je_iphone
#       data: 
#         title: 'Medicine Alert'
#         message: 'Please take your pill'
#         data: 
#           push: 
#             category: 'temp_med'

# - alias: Medicine 4
#   trigger:
#     - platform: time
#       minutes: '/15'
#       seconds: '00'
#   condition:
#     condition: and
#     conditions: 
#       - condition: numeric_state
#         entity_id: input_number.antibiotic
#         below: 4
#       - condition: time
#         after: '21:00:00'
#   action: 
#     - service: notify.ios_je_iphone
#       data: 
#         title: 'Medicine Alert'
#         message: 'Please take your pill'
#         data: 
#           push: 
#             category: 'temp_med'
