automation:
  - alias: Tablet Already taken
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: TABLET_TAKEN
    action:
      - service: notify.ios_je_iphone
        data:
          message: "Great job!"
      - service: input_boolean.turn_on
        entity_id: input_boolean.medicine

  - alias: Remind Me Later
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: TABLET_SNOOZE
    action:
      - service: notify.ios_je_iphone
        data:
          message: "Ok. I will remind you later..."
      - delay: 0:15
      - service: notify.ios_je_iphone
        data:
          message: "Snooze Over! Take your medicine!"

  - alias: Medicine Reminder
    initial_state: true
    trigger:
      - platform: time
        minutes: '45'
        seconds: '00'
      - platform: time
        at: '21:30:00'
      - platform: state
        entity_id: device_tracker.je_iphone
        to: 'home'

    condition:
      - condition: time
        after: '21:30:00'
      - condition: state
        entity_id: device_tracker.je_iphone
        state: 'home'
      - condition: state
        entity_id: input_boolean.medicine
        state: 'off'

    action:
      - service: notify.ios_je_iphone
        data:
          title: "Medicine Alert!"
          message: "Please take your Medicine!"
          data:
            push:
              category: "tablet"
            action_data:
              entity_id: light.test
              my_custom_data: foo_bar

## Reminders to take my Medicine! - End.